<?php 
	if ($this->hasCity)
	{
?>
<h1 id="cityname">
Events <?php echo $this->city ?>
</h1>
<h2>
<?= $this->start . " - " . $this->end ?>
</h2>
<?= $this->partial("shared/_nearbycities.phtml", array( "div" => "city_search", "cities" => $this->nearby, "form" => $this->form)) ?>
<div id="events">
<?= $this->partial("shared/_eventmap.phtml", array( "events" => $this->events, "location" => $this->location )); ?>
</div>
<?php
        }
        else
        {
                echo "<div>Sorry, we couldn't figure out what city you're from. You can still search for events though!</div>";
        }
?>
<script type="text/javascript">
$(function() {
	findierock.bindSearch("#CityForm", "#search", "/Events/search-for-cities", "#citylist" );
	findierock.bindAutoComplete("#city", "/Events/get-cities?callback=?", 2);
});
</script>