<div>
		<a href='http://www.facebook.com/share.php?u=<?= $this->url ?>' target='_blank'><img src='/img/facebook.gif' border='0'  alt='' title='Share this indie artist on Facebook'></a>
		<a href='http://digg.com/submit?url=<?= $this->url ?>' target='_blank'><img src='/img/diggThisDigger.png' border='0' alt='' title='Digg this!' /></a>
		<a href='http://ping.fm/ref/?link=<?= $this->url ?>&amp;title=<?= $this->title ?>' target='_blank'><img src='/img/pingfm.png' border='0'  alt='' title='Share this on Ping.fm'></a>
		<a href='http://del.icio.us/post?url=http%3A%2F%2Foverhear.com%2Fartists%2Fthe_raftsmen&amp;title=<?= $this->title ?>' target='_blank'><img src='/img/delicious.gif' alt='' title='Bookmark this on Del.icio.us' border='0'></a>
		<a href='http://www.stumbleupon.com/submit?url=<?= $this->url ?>&amp;title=<?= $this->title ?>' target='_blank'><img border='0' src='/img/stumbleupon_sq.png' alt='' title='Make this a favourite site on StumbleUpon'></a>
		<a href='http://reddit.com/submit?url=<?= $this->url ?>&amp;title=<?= $this->title ?>' target='_blank'><img src='/img//reddit.png' alt='' title='Bookmark this on reddit' border='0'></a>
		<a href='http://www.furl.net/store?s=f&amp;to=0&amp;u=<?= $this->url ?>&amp;ti=<?= $this->title ?>' target='_blank'><img src='/img/furl.gif' alt='' title='Bookmark this on furl' border='0'></a>
		<a href='http://ma.gnolia.com/bookmarklet/snap/add?url=<?= $this->url ?>&amp;title=<?= $this->title ?>' target='_blank'><img src='/img/magnolia.png' alt='' title='Bookmark this on Magnolia' border='0'></a>
		<a href='http://myweb.yahoo.com/myresults/bookmarklet?u=<?= $this->url ?>&amp;t=<?= $this->title ?>&amp;ei=UTF' target='_blank'><img src='/img/yahoo16.png' alt='' title='Bookmark this on myweb Yahoo' border='0'></a>
		<a href='http://www.google.com/bookmarks/mark?op=edit&amp;output=popup&amp;bkmk=<?= $this->url ?>&amp;title=<?= $this->title ?>' target='_blank'><img src='/img/goog.png' alt='' title='Bookmark this on Google' border='0'></a>
		<a href='http://www.myspace.com/Modules/PostTo/Pages/?u=<?= $this->url ?>&amp;t=<?= $this->title ?>' target='_blank'><img src='/img/myspace.png' alt='' title='Post this to MySpace' border='0'></a>
</div>