<dl class="post_meta" style="width: 200px">
        <dt class="meta_data">Sponsors</dt>
        <dt>
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-7136387287433354";
	google_ad_slot = "1381057361";
	google_ad_width = 200;
	google_ad_height = 200;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	</dt>
</dl>


