<dl class="post_meta">
        <dt class="meta_data">Sponsors</dt>
        <dt>
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-7136387287433354";
	/* Findie Vertical */
	google_ad_slot = <?= $this->adId ?>;
	google_ad_width = 120;
	google_ad_height = 600;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	</dt>
</dl>
