<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<title><?php if (isset($this->title)) {echo $this->title;} else {echo "Findie Rock";} ?></title>
<?php echo $this->headMeta() ?>
<link type="image/png" href="/favicon.ico" />
<link rel="alternate" type="application/rss+xml" title="FindieRock RSS Feed" href="/blog/feed/" />
<?php if(APPLICATION_ENV == "development")  { ?>
<link rel="stylesheet" href="/css/style.css" />
<link rel="stylesheet" href="/css/jquery-ui-1.8.5.custom.css" />
<link rel="stylesheet" href="/css/jquery.ui.stars.css" />
<?php } else { ?>
<link rel="stylesheet" href="/css/findie.css" type="text/css" />
<?php } ?>
<!--[if lt IE 7]>
<link rel="stylesheet" href="/ie6.css" type="text/css" />
<![endif]-->
<link rel='index' title='FindieRock' href='http://www.findierock.com/' />
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js'></script>
</head>
<body>
<div id="spinner"></div>
<div id="wrapper">
<div id="header">
<div id="header_top">
<div id="logo">
	<h1>
		<a id="logo_image" href="/"><img title="Findie Rock" alt="Findie Rock" src="/img/logo.png" /></a>
	</h1>
</div>
<div class="header_menu"><?= $this->navigation()->menu()->setUlClass("menu"); ?></div>
<div style="clear: both;"></div>
</div>
</div>
<!-- #header end -->
<div id="contents" class="clearfix">
<div id="left_col">
<div id='header_meta'>
	<ul id="bread_crumb"><li>
	<? 
		$crumbs = $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(false)
							->setRenderInvisible(true)->setSeparator(" » ");
		if (strpos($crumbs, "Home") === false)
		{
			if (trim($crumbs) != "")
			{
				$crumbs = " » " . $crumbs;
			}
			$crumbs = "<a href='/'>Home</a>" . $crumbs;
		}
		echo $crumbs;
	?>
	</li></ul>
</div>
<div class="post_odd">
<div class="post clearfix">
<div class="post_content_wrapper">
	<div class="post_content">
	<div style="text-align: center; margin-top: -25px;">	
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-7136387287433354";
	google_ad_slot = "4976610308";
	google_ad_width = 468;
	google_ad_height = 60;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	</div>
	<?= $this->layout()->content ?>
	</div>
</div>
<?= $this->render( $this->sidebarLayout ); ?>
</div>
</div>
</div>
<!-- #left_col end -->
<div id="right_col">
<div id="information_area" class="clearfix">
<div class="side_box" id="information">
	<h3>Information</h3>
	<div id="information_contents">
		<strong>Findie Rock was made so you can "find indie rock"</strong>, hence the clever name! Events, Albums, Venues and Artists...
		You can search or browse them all at your leisure. Find out what's really happening in your area!
	</div>
</div>
<div id="entries_rss"><a href="/blog/feed/"
	title="Entries RSS">RSS FEED</a>
</div>
</div>
<?= $this->render("_google_ads_right.phtml"); ?>
<?= $this->render("_feed_right.phtml"); ?>
</div>
<!-- #right_col end --></div>
<!-- #contents end -->
<div id="footer">
<ul id="copyright">
	<li style="background: none;">Copyright &copy;&nbsp; 2010-2011 &nbsp;<a
		href="/">FindieRock.com</a></li>
</ul>
</div>
</div>
<!-- #wrapper end -->
<div id="return_top"><a href="#wrapper">&nbsp;</a></div>
<? echo $this->render('_analytics.phtml'); ?>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
<?php if (APPLICATION_ENV == "development") { ?>
<script type='text/javascript' src='/js/findierock.js'></script>
<script type='text/javascript' src='/js/jscript.js'></script>
<script type='text/javascript' src='/js/jquery.ui.timepicker.js'></script>
<script type='text/javascript' src='/js/jquery.ui.stars.js'></script>
<?php } else { ?>
<script type='text/javascript' src='/js/findie.javascript'></script>
<?php }?>
<script type="text/javascript">
$(function() {
	$("#spinner").ajaxStart(function() {
		$(this).fadeIn("fast");
	}).ajaxStop(function() {
		$(this).fadeOut("fast");
	});
});
</script>
</body>
</html>
