<?php
// This file generated by Propel 1.5.3 convert-conf target
// from XML runtime conf file /home/ahsile/Documents/Programming/findierock/application/configs/conf/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'findierock_dev' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => '',
        'user' => '',
        'password' => '',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'findierock_prod' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => '',
        'user' => '',
        'password' => '',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'findierock_prod',
  ),
  'generator_version' => '1.5.3',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-findierock-conf.php');
return $conf;
