-- Change Venue Rating
ALTER TABLE `venuerating` DROP FOREIGN KEY `FK_VENUERATING_MEMBER` ;
ALTER TABLE `venuerating` DROP INDEX `FK_VENUERATING_MEMBER`
ALTER TABLE `venuerating` CHANGE `MemberId` `UserId` INT( 11 ) NOT NULL;
ALTER TABLE `venuerating` ADD CONSTRAINT `FK_VENUERATING_USER` FOREIGN KEY (`UserId`) REFERENCES `user` (`UserId`) ON DELETE NO ACTION ON UPDATE NO ACTION;
-- Change Artist Rating
ALTER TABLE `artistrating` DROP FOREIGN KEY `FK_ARTISTRATING_MEMBER`;
ALTER TABLE `artistrating` DROP INDEX `FK_ARTISTRATING_MEMBER`;
ALTER TABLE `artistrating` CHANGE `MemberId` `UserId` INT( 11 ) NOT NULL;
ALTER TABLE `artistrating` ADD CONSTRAINT `FK_ARTISTRATING_USER` FOREIGN KEY (`UserId`) REFERENCES `user` (`UserId`) ON DELETE NO ACTION ON UPDATE NO ACTION;
-- Kill Member Table
DROP TABLE `member`;
-- Create Album Rating
CREATE TABLE IF NOT EXISTS `albumrating` (
  `AlbumId` int(11) NOT NULL,
  `UserId` int(11) NOT NULL,
  `Rating` smallint(6) DEFAULT NULL,
  `Comments` text,
  PRIMARY KEY (`AlbumId`,`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `albumrating` ADD CONSTRAINT `FK_ALBUMRATING_ALBUM` FOREIGN KEY (`AlbumId`) REFERENCES `album` (`AlbumId`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `albumrating` ADD CONSTRAINT `FK_ALBUMRATING_USER` FOREIGN KEY (`UserId`) REFERENCES `user` (`UserId`) ON DELETE NO ACTION ON UPDATE NO ACTION;


